### ISSUE TITLE
Transcode doesn't work on Raspberry Pi 4 4Gb

### ISSUE THREAD

**Issue by nimamahmoudi** [hassio-addons/addon-plex#107]
# Problem/Motivation

> Transcode doesn't work on Raspberry Pi 4, it creates the folder `/share/transcode/Transcode/Sessions`, but doesn't create anything in it. The video fails to play on the browser with 404 errors for `/transcode` paths.

## Expected behavior

> Playing the video

## Actual behavior

> Gave a series of 404 errors and doesn't create any transcode files.

## Steps to reproduce

> Run the add-on on Raspberry Pi 4 4Gb

## Proposed changes

> No proposed changes. I have no idea why this is happening.

**Comment by sinclairpaul** [comment]
Please provide relevant logs, also for expectations, transcoding is a CPU intensive task, I doubt that running on a Pi (while running other services) will meet your expectations.

**Comment by nimamahmoudi** [comment]
It doesn't generate any relevant logs, even though I have set the log level to debug:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Plex Media Server
 Recorded media, live TV, online news, and podcasts ready to stream.
-----------------------------------------------------------
 Add-on version: 2.6.1
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.6.6
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] plex.sh: executing... 
[cont-init.d] plex.sh: exited 0.
[cont-init.d] webtools.sh: executing... 
[cont-init.d] webtools.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:16:38] INFO: Starting the Plex Media Server...
```

I actually don't need transcoding if I can use the direct play on the web. This is an option that is available in the applications (I use the Android app and the Roku TV app and both work fine) but isn't available in the web version of plex.

However, I also think that RPi 4 should have enough computational power to support only one stream from 1080p to 1080p (again, I would rather use direct play, but it isn't available here). I am using the same settings on a cloud-based VM and it uses 5-10% CPU usage while running for a single stream, but I would rather host this in my house.

**Comment by sinclairpaul** [comment]
> but isn't available in the web version of plex

Not sure what we can do about that, the addon wraps Plex itself. 

> I am using the same settings on a cloud-based VM

And is that ARM based?, not trying to sound off, but there are certain expectations you need for running on the platform you have.

**Comment by nimamahmoudi** [comment]
@sinclairpaul: Regarding the VM, it is not ARM-based, but I was assuming that 100% of a 4-core ARM-based CPU should beat 10% of a 2-core shared Intel CPU. However, the problem might be on the plex side.

**Comment by sinclairpaul** [comment]
I think your assumption maybe slightly incorrect.  I am going to close this out, its likely a performance issue.
