### ISSUE TITLE
URL for updated Plex is wrong

### ISSUE THREAD

**Issue by tsvi** [hassio-addons/addon-plex#11]
# Problem/Motivation

> When trying to install the son it won't start due to http parsing error
Looking at the commits, I tried accessing the updated URL. It resolves to file not found

## Expected behavior

> Add-on not to report errors and start correctly

## Actual behavior

> Reports errors and is stuck in a loop trying to start.

## Steps to reproduce

> Install Plex add-on. Insert claim key. Press start.

## Proposed changes

> Fix the latest commit changing the URL to the correct path.

**Comment by frenck** [comment]
Please provide logs.

**Comment by tsvi** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing...
-----------------------------------------------------------
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 Hass.io Add-on:  v
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured

parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 From:
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 By:
-----------------------------------------------------------
 aarch64 / HassOS 1.12 / HA 0.82.1 / SU 140 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing...
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing...
DEBUG: Requested API resource: http://hassio/supervisor/ping
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {}}
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_plex/info
DEBUG: API HTTP Response code: 403
DEBUG: API Response: 403: Forbidden
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_plex/info
DEBUG: API HTTP Response code: 403
DEBUG: API Response: 403: Forbidden
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-first-run.sh: executing...
INFO: First run! Initializing configuration files...
DEBUG: Generating unique serial & client id's...
DEBUG:
FATAL: Something went wrong contacting the Plex API
FATAL: Maybe your claim code is wrong or expired?
[cont-init.d] 10-first-run.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing...
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.

 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

**Comment by frenck** [comment]
Please use a valid claim code, as per installation instructions.

```
FATAL: Something went wrong contacting the Plex API
FATAL: Maybe your claim code is wrong or expired?
```

**Comment by tsvi** [comment]
Yes, it seems my claim code expired, but even with a new claim code it doesn't work:

```
Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 Hass.io Add-on:  v
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 From: 
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 By: 
-----------------------------------------------------------
 aarch64 / HassOS 1.13 / HA 0.82.1 / SU 140 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to DEBUG
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 
DEBUG: Requested API resource: http://hassio/supervisor/ping
DEBUG: API HTTP Response code: 200
DEBUG: API Response: {"result": "ok", "data": {}}
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_plex/info
DEBUG: API HTTP Response code: 403
DEBUG: API Response: 403: Forbidden
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
DEBUG: Requested API resource: http://hassio/addons/a0d7b954_plex/info
DEBUG: API HTTP Response code: 403
DEBUG: API Response: 403: Forbidden
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-first-run.sh: executing... 
[cont-init.d] 10-first-run.sh: exited 0.
[cont-init.d] 20-webtools.sh: executing... 
[cont-init.d] 20-webtools.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting the Plex Media Server
./run: line 18: /usr/lib/plexmediaserver/Plex Media Server: No such file or directory
INFO: Starting the Plex Media Server
./run: line 18: /usr/lib/plexmediaserver/Plex Media Server: No such file or directory
INFO: Starting the Plex Media Server
./run: line 18: /usr/lib/plexmediaserver/Plex Media Server: No such file or directory
INFO: Starting the Plex Media Server
./run: line 18: /usr/lib/plexmediaserver/Plex Media Server: No such file or directory
```

**Comment by tsvi** [comment]
@frencknpmease reopen as the issue seems to continue

**Comment by frenck** [comment]
aah 64 bit. This is a known issue (to me) without a solution yet.
I really need to update the add-on store to blacklist it for arm64

**Comment by tsvi** [comment]
:(

Any plans on supporting 64 bit? Is it possible?

Thanks for looking into it.

**Comment by frenck** [comment]
This is not a matter of willing to support, this is a matter of an issue without a solution.

**Comment by tsvi** [comment]
Ok. Thanks you very much
