### ISSUE TITLE
Data/Config Folder Access

### ISSUE THREAD

**Issue by SauRoNZA** [hassio-addons/addon-plex#120]
# Problem/Motivation

It's my understanding that with a Hass.io install I should be seeing the config/data folders for the Docker under /usr/share/hassio but I don't even have that folder.

/root does have a symlink in to /addons but both of those are also just blank. 

Plex and SSH adding are running and working without issue though.

Looking to migrate my Plex server from an UnRAID instance to my Home Assistant box and really struggling in this regard.

## Expected behavior

To access the appdata folder under or /usr/share/hassio or what appears might also be /root but there simply isn't anything populated there.

## Actual behavior

Blank folder mappings everywhere. Not just this addon but seemingly all of them.

## Steps to reproduce

Checked both a Raspberry Pi and Generic X86 installation and same behaviour.

## Proposed changes

Probably just user error missing some documentation.

**Comment by sinclairpaul** [comment]
Hi, we use Github for issue tracking.

You will get a better response to your questions around Home Assistant itself on the forums or Discord, as this is not a issue relating to this addon itself.

Thanks
