### ISSUE TITLE
Port 1900 not exposed 

### ISSUE THREAD

**Issue by maframan** [hassio-addons/addon-plex#137]
# Problem/Motivation
Why is not exposed the 1900 udp port? I need this port For dlna Integration 

thanks and regards

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Port 1900 is used by a lot of add-ons and integrations, and causes conflicts really fast. Additionally, to make it work properly, it requires the add-on to run on the host network as well (with additional unneeded conflict risks).

For these reasons; this add-on does not support DLNA, which is documented as well:

<https://github.com/hassio-addons/addon-plex/blob/main/plex/DOCS.md#known-issues-and-limitations>

**Comment by maframan** [comment]
Is it possible to enable dlna capability? Do i do?
I don't have port conflit on both container and host.

Thanks and regards
Francesco

Il giorno mar 30 nov 2021 alle ore 08:37 Franck Nijhof <
***@***.***> ha scritto:

**Comment by frenck** [comment]
> Is it possible to enable dlna capability? Do i do?

No. As listed in the add-on documentation and limitation section.
