### ISSUE TITLE
Only allows manual updates / auto update not working.

### ISSUE THREAD

**Issue by RickSanchezC136** [hassio-addons/addon-plex#152]
# Problem/Motivation

Fresh install of proxmox, home assistant supervised and plex add-on.
This is what I see in the updates section of my plex server config. 

![image](https://user-images.githubusercontent.com/99632096/172256186-3e6a1e39-17ac-4155-adb6-27f0f7cde526.png)

## Expected behavior

I remember updates being automatic, I thought it should give me a one-click type option to update from this spot.

## Actual behavior

It only seems to give the option to update plex manually.

## Steps to reproduce

1. Install proxmox on new hardware
2. Create VM and install Home Assistant supervised OS
3. Install Plex add-on
4. Login to plex web ui, goto settings, find the update section

## Proposed changes

Not sure what's wrong so I can't suggest what should be changed.

**Comment by AlecRust** [comment]
Nothing is wrong, this addon pins the version of Plex, and it's a bit behind right now.
