### ISSUE TITLE
Cant map my network drive to plex

### ISSUE THREAD

**Issue by Markobu98** [hassio-addons/addon-plex#157]
# Problem/Motivation

I have HA running as a VM on proxmox and my network show on truenas as a VM on proxmox. I have created a shared folder in hassOS but cant mount the network drive

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

 mkdir /mnt/data/supervisor/share/media_library
created a folder to mount my shared folder to

mount -t cifs -o username=YOUR_USER,password=YOUR_PASSWORD //YOUR_SHARED_SERVER_IP/YOUR_SHARED_FOLDER /mnt/data/supervisor/share/media_library
wanted to mount the folder but I get the error message:

mount: /mnt/data/supervisor/share/media_library: cannot mount //YOUR_SHAREDD_SERVER_IP/YOUR_SHARED_SERVER read-only

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> I have created a shared folder in hassOS but cant mount the network drive

Correct, Home Assistant does not support mapping network drives. This is not an add-on limitation.
