### ISSUE TITLE
Option to mount network share?

### ISSUE THREAD

**Issue by bobloadmire** [hassio-addons/addon-plex#159]
# Problem/Motivation

Recently used the Nextcloud add-on and it has the ability to mount a network share on the container via the config, can you do the same with this add-on? My media is on a network share. Not seeing anything in the documentation.

## Expected behavior

ability to mount network share with SMB

## Actual behavior
not documented if it exists.

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

document or add the functionality.

**Comment by nathang21** [comment]
You might be interested in trying this fork of the addon, which supports local/network disks.   
https://github.com/alexbelgium/hassio-addons/tree/master/plex

**Comment by bobloadmire** [comment]
Bless you, thank you

**Comment by frenck** [comment]
Closing it on this end. This is something Ha should support, not an add-on. I will therefore not add support in this add-on for it.

**Comment by bobloadmire** [comment]
Yeah what's the deal with HA still not support network disks after all
these years?

**Comment by frenck** [comment]
🤷 its an open source project, some has to stand up and contribute it.

**Comment by bobloadmire** [comment]
no, i mean, they have added so much stuff thats insanely more complicated than add the ability to attach to a storage medium. I'm assuming it must be against their philosophy of what HA is supposed to be, but I haven't found a statement on it, thought maybe you knew.

**Comment by frenck** [comment]
I know it is wishlist item. The things that van de done Is huge. In the end, most feature rely on contributions made, that is how open source projects work.
