### ISSUE TITLE
Doesn't open after last update (V:3.1.1)

### ISSUE THREAD

**Issue by emre299** [hassio-addons/addon-plex#169]
Hi,
Plex, which I have been using for 1 year without any errors, is not working after the update I just made. Even if I restore the backup, plex doesn't work. 
![plex](https://user-images.githubusercontent.com/32033063/190984919-8dba0c51-1022-43ce-8bc9-195af59c1c2f.PNG)

I can't get log file.
No changes HA other than Plex update.
What can I do to fix it?

**Comment by frenck** [comment]
Port 1900 is already in use, that is not an add-on issue.

Please free up port 1900 or disable it in the add-on network configuration by emptying the field.

As the add-on isn't started yet, nothing of this is in control of the add-on.

../Frenck

**Comment by emre299** [comment]
ok but it wasn't happening before and how do i fix it?
Can you help me?

**Comment by frenck** [comment]
I already answered what to do above. Again, this is not related to the addon or addon uograde, but related to your system that you manage.

**Comment by emre299** [comment]
![unknown](https://user-images.githubusercontent.com/32033063/191496821-7f69f416-cecd-4022-9d4e-ce6b69e6b5f8.png)

Hello again, this port is empty. Still plex gives the same error and won't turn on. I can't use my favorite plex.

**Comment by frenck** [comment]
You are scanning TCP ports...
