### ISSUE TITLE
Addon not available on your system

### ISSUE THREAD

**Issue by RipCurrent** [hassio-addons/addon-plex#17]
Hi
Newbie on this, can’t find an answer elsewhere for this
Have hassio (64bit) up and running on a raspberry pi 3 model b, 32g sd card.
Getting the “this addon is not available on your system” for the plex media server component.

I see issues with arm7, this is arm8 according Wikipedia. Guessing this setup not supported?
Thx

![3e0cbd6e-9199-4b41-ae63-e3deb09e911f](https://user-images.githubusercontent.com/8657359/52183167-02e0b200-27fd-11e9-98c4-77ce09cfa7ec.png)

**Comment by frenck** [comment]
Plex is simply not made available for 64 bit ARM (aarch64), hence the add-on does not support it.
