### ISSUE TITLE
after update to 3.1.1 plex won't start anymore

### ISSUE THREAD

**Issue by dominiquevocat** [hassio-addons/addon-plex#170]
# Problem/Motivation

after upgrade to 3.1.1 plex won't start anymore

## Expected behavior

plex just runs

## Actual behavior

borks out in plex/rootfs/etc/cont-init.d/plex.sh in line 59

## Steps to reproduce

update plex to 3.1.1

## Proposed changes

the file claim_code was empty and the curl did not deliver any usefull result causing plex not to run.

- redacted output of the curl line with -v :

root@blackbox:~# curl -v --write-out '\n%{http_code}' --request POST -H "X-Plex-Client-Identifier: xxxxxxxxxxxxxx" -H 'X-Plex-Product: Plex Media Server' -H 'X-Plex-Version: 1.1' -H 'X-Plex-Provides: server' -H 'X-Plex-Platform: Linux' -H 'X-Plex-Platform-Version: 1.0' -H 'X-Plex-Device-Name: PlexMediaServer' -H 'X-Plex-Device: Linux' "https://plex.tv/api/claim/exchange?token=claim-xxxxxxxxx"
*   Trying 54.229.236.47:443...
* Connected to plex.tv (54.229.236.47) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=CH; ST=Nidwalden; L=Stans; O=Plex GmbH; CN=*.plex.tv
*  start date: Sep 14 00:00:00 2022 GMT
*  expire date: Sep 23 23:59:59 2023 GMT
*  subjectAltName: host "plex.tv" matched cert's "plex.tv"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Using Stream ID: 1 (easy handle 0x562f336b7930)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /api/claim/exchange?token=claim-xxxxxxxxxxxxx HTTP/2
> Host: plex.tv
> user-agent: curl/7.81.0
> accept: */*
> x-plex-client-identifier: xxxxxxxxxxxxxxxxxxx
> x-plex-product: Plex Media Server
> x-plex-version: 1.1
> x-plex-provides: server
> x-plex-platform: Linux
> x-plex-platform-version: 1.0
> x-plex-device-name: PlexMediaServer
> x-plex-device: Linux
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 403
< cache-control: no-cache
< content-type: application/xml
< date: Tue, 20 Sep 2022 20:44:05 GMT
< referrer-policy: origin-when-cross-origin
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< vary: Origin
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-request-id: b4788fc1-1b9c-4802-a37e-a11685efdc70
< x-runtime: 0.175935
< x-xss-protection: 1; mode=block
<
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host plex.tv left intact

**Comment by SirGoodenough** [comment]
same here.
I redacted the claim code, have been using it for quite a while now.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Plex Media Server
 Recorded media, live TV, online news, and podcasts ready to stream.
-----------------------------------------------------------
 Add-on version: 3.1.1
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2022.9.5
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
Log level is set to TRACE
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/plex.sh
[02:37:06] TRACE: bashio::fs.file_exists: /data/claim_code
[02:37:06] TRACE: bashio::fs.file_exists: /data/Plex Media Server/Preferences.xml
[02:37:06] TRACE: bashio::config: claim_code
[02:37:06] TRACE: bashio::addon.config
[02:37:06] TRACE: bashio::cache.exists: addons.self.options.config
[02:37:06] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[02:37:06] TRACE: bashio::cache.get: addons.self.options.config
[02:37:06] TRACE: bashio::cache.exists: addons.self.options.config
[02:37:06] TRACE: bashio::fs.file_exists: /tmp/.bashio/addons.self.options.config.cache
[02:37:06] TRACE: bashio::jq: {"claim_code":"claim-58W_redacted-m","log_level":"trace"} if (.claim_code == null) then
            null
        elif (.claim_code | type == "string") then
            .claim_code // empty
        elif (.claim_code | type == "boolean") then
            .claim_code // false
        elif (.claim_code | type == "array") then
            if (.claim_code == []) then
                empty
            else
                .claim_code[]
            end
        elif (.claim_code | type == "object") then
            if (.claim_code == {}) then
                empty
            else
                .claim_code
            end
        else
            .claim_code
        end
[02:37:06] TRACE: bashio::var.has_value: claim-58W_redacted-m
[02:37:06] DEBUG: Generating unique serial & client id's...
[02:37:07] DEBUG: 
[02:37:07] FATAL: 
[02:37:07] FATAL: Something went wrong contacting the Plex API
[02:37:07] FATAL: Maybe your claim code is wrong or expired?
[02:37:07] TRACE: bashio::exit.nok:
[02:37:07] TRACE: bashio::var.has_value: 
cont-init: info: /etc/cont-init.d/plex.sh exited 1
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by AlecRust** [comment]
You have already tried with a new claim code from https://www.plex.tv/claim right?

**Comment by emre299** [comment]
After the update, I also do not open plex. Does it give an error about "port 1900"

**Comment by SirGoodenough** [comment]
I have

**Comment by guiofranca** [comment]
I've had the same problem. The log mentions to update the claim code so I did it. No good. Then I had to rollback to 3.1.0 and it's working again. I also disabled auto updates for this addon.

**Comment by michelebossa** [comment]
Hello i have changed the claim code and it is worked for me.

**Comment by tbaumann** [comment]
Same happened to me. It was really obscure. I could see no logs. The docker container stopped very shortly.

Saw this here, got a new claim code and it's running again.

**Comment by chrisghz** [comment]
I have the same issue with this new update! Rolled back to 3.1.0 and its all working again. Do we know if there is going to be a fix for this?
