### ISSUE TITLE
What is the Media Library folder path in Plex?

### ISSUE THREAD

**Issue by Mari143** [hassio-addons/addon-plex#190]
Media Library in Plex is not working when the folder path is mapped to NAS connected with HA

I want to be able make a library in Plex which is mapped to an external drive connected to HA. I'm not sure what folder path to use to be able to achieve this. 

/\\192.168.0.1/share/NAS/music

This seems not work. I have tried everything. Is this not possible with this add on? If it is possible can you please tell me how it can be done.

Thanks!

**Comment by frenck** [comment]
>  the folder path is mapped to NAS connected with HA

HA Doesn't support such a thing...

So, if it ain't working, it is because of your own workarounds (and thus this is your own problem to solve).

../Frenck
