### ISSUE TITLE
Plex Server Setup

### ISSUE THREAD

**Issue by PatrickNET01** [hassio-addons/addon-plex#191]
# Problem/Motivation

> Plex tries to set up my server every time I open it and then crashes. "Please wait a moment while Plex starts." spinning circle and crash with "A problem has been detected with a core component of Plex Media Server."  I tried to reinstall many times.

## Expected behavior

> Set up once at first start.

## Actual behavior

> Described above. I can use it if i bypass with the click on the finish button but it has media library scanning issues etc..

## Steps to reproduce

> Open/reload the local server page. -> http://homeassistant.local:32400/

## Proposed changes

> I can bypass it if i click to the Finish menu but it starts again if i reload the page which is not normal.

**Comment by frenck** [comment]
Maybe an add blocker of some sort? I'm not able to reproduce this issue at least.

**Comment by Nattle** [comment]
I'm running into a similar issue. 

Just setup HA this morning and have a handful of things setup. I can install the Plex server and start it. I see the cpu jump and I get a hostname (ex: `a0d7b954-plex`). The icon shows green but if I refresh the page it turns red. At no point is the web UI accessible via port 32400.
