### ISSUE TITLE
How do I Update web media server?

### ISSUE THREAD

**Issue by chatz86** [hassio-addons/addon-plex#198]
# Problem/Motivation
Hey guys. I've installed the Plex media server for Home OS on a nuc and all appears to be working fine. Everything is up to date on HAOS and HACS. App is installed on phone and PC however I get this message about updating on the Plex Web desktop.

> (Why the issue was filed)
Issues installing update on web media server.
## Expected behavior
Unknown 
> (What you expected to happen)
Update the server for latest bug fixes etc.
## Actual behavior
Not sure what to do. 
> (What actually happened)
I've downloaded the .SPK file but I've tried following instructions online and can't get it to update. Any help would be much appreciated.
![20230627_232405~2](https://github.com/hassio-addons/addon-plex/assets/82794294/d2bd2643-b82a-4986-801e-7ae2b2b190b0)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
>  Thought they may be a work around.

I don't do or support workarounds.

../Frenck
