### ISSUE TITLE
Addon could not start with activated webtools

### ISSUE THREAD

**Issue by DanielXYZ2000** [hassio-addons/addon-plex#2]
Webpage not reachable, because startup ws terminated.
A link could not be setup 
ln: target '/data/Plex Media Server/Plug-ins/' is not a directory:
see log file
```
...
[cont-init.d] 10-first-run.sh: exited 0.
[cont-init.d] 20-webtools.sh: executing... 
INFO: Enabling WebTools plugin...
ln: target '/data/Plex Media Server/Plug-ins/' is not a directory: No such file or directory
[cont-init.d] 20-webtools.sh: exited 1.
...
[s6-finish] sending all processes the TERM signal.
```

Disabling the webtools works (Open Web UI works)

**Comment by frenck** [comment]
Interesting @DanielXYZ2000.

What platform are you using? Could you describe your setup?

**Comment by frenck** [comment]
Issue has been fixed in the `master` branch / dev version. Will be generally available in the next release.

**Comment by DanielXYZ2000** [comment]
Hi, Sorry I was on business trip and could not respond.
Thanks for the fix!
