### ISSUE TITLE
The Plex DLNA Server is not visible on TV

### ISSUE THREAD

**Issue by jam830** [hassio-addons/addon-plex#211]
# Problem/Motivation

> The Plex DLNA Server is not visible on TV (and other device)

## Steps to reproduce

> Go to Plex web GUI -> Settings -> DLNA -> Enable server DLNA

## Proposed changes

Try to expose port 1900 (https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/)

**Comment by frenck** [comment]
As per documentation of this add-on:

![CleanShot 2023-12-06 at 09 44 32@2x](https://github.com/hassio-addons/addon-plex/assets/195327/6ca4589a-3706-408a-8ad5-ef9eec3e5b3f)
