### ISSUE TITLE
NTFS is not supported

### ISSUE THREAD

**Issue by oroberman** [hassio-addons/addon-plex#223]
Installed your plugin and inserted Western Digital HDD on the USB.
From the logs I see:
---------------------------------------------------
[16:51:55] INFO: Available Disks for mounting :
NAME        LABEL           SIZE FSTYPE   RO
└─sda1      My Book         3.6T ntfs      0
---------------------------------------------------
Supported fs :  ext3 ext2 ext4 squashfs vfat msdos f2fs fuseblk
Inspired from : github.com/dianlight
---------------------------------------------------
Local Disks mounting...
... sda1 is a physical device
[16:51:55] FATAL: : ntfs type for sda1 is not supported

what is my options to mount the ntfs

**Comment by frenck** [comment]
This add-on has no mounting handling at all? Here is this?

../Frenck

**Comment by frenck** [comment]
Closing this issue, as there has been no response.

../Frenck
