### ISSUE TITLE
Missing service SERVICE PLEX.REFRESH_LIBRARY

### ISSUE THREAD

**Issue by WiseMarius** [hassio-addons/addon-plex#227]
# Problem/Motivation

Missing service SERVICE PLEX.REFRESH_LIBRARY

## Expected behavior

To see in Developer Tools -> Services the entry SERVICE PLEX.REFRESH_LIBRARY

## Actual behavior

Missing service SERVICE PLEX.REFRESH_LIBRARY in Developer Tools

## Steps to reproduce

Install the addon, go to Developer Tools -> Services and notice how the entry SERVICE PLEX.REFRESH_LIBRARY is missing

## Proposed changes

make it work

**Comment by frenck** [comment]
I think you are in the wrong place. This is an add-on, add-ons do not provide services.

You are mixing up integration vs add-ons in Home Assistant I think.

../Frenck

**Comment by WiseMarius** [comment]
You are right. Sorry for the confusion and thanks for the quick response :)

**Comment by frenck** [comment]
<img src="https://media0.giphy.com/media/4GRRBtKrdiFDa/giphy.gif"/>
