### ISSUE TITLE
Plex Movie playback not working on TVs

### ISSUE THREAD

**Issue by BombeiJay** [hassio-addons/addon-plex#230]
Hey, i have Home Assistant on a Respberry Pi 5 (8GB).
Movies do not work on TV via the Plex app it loads all the time. On my cell phone and PC there were no problems with the playback of movies.

HA Plex Log:
 Add-on version: 3.5.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
 
 No Errors.
 
 Plex WebUI Log when is start a movie on a TV:
 
![image](https://github.com/user-attachments/assets/fcdc259b-c19f-45a4-8e3f-af0fcf278ec1)

the errors are looping until i stop playback on TV

**Comment by Want100Cookies** [comment]
It looks like your TV does not have support to play the MP4 file with mpeg2video codec. And the Pi does not do transcoding. Try downloading something with another codec.
