### ISSUE TITLE
No Remote Access

### ISSUE THREAD

**Issue by bigverm23** [hassio-addons/addon-plex#234]
# Problem/Motivation

> I am unable to obtain remote access due to the host IP showing as a docker IP.

## Expected behavior

> Remote access should show Private IP as host IP and be able to port forward by manually specifying port 32400

## Actual behavior

> 
![image](https://github.com/user-attachments/assets/6adb618a-cf05-42c1-9370-87af87765e85)

**Comment by frenck** [comment]
See the documentation: https://github.com/hassio-addons/addon-plex/blob/main/plex/DOCS.md#solving-connection-issues-with-plex

**Comment by bigverm23** [comment]
Appreciate the response but putting any combination of host and external urls in seemingly has no effect.  I have the host machine Ip:port, nginx reverse proxy address https://plex..., and docker Ip:port

**Comment by silvertoes93** [comment]
I had this issue and resolved by setting up a port forwarding rule on my router. This was needed in addition to the fix set out in the documentation.
