### ISSUE TITLE
Can't start addon_a0d7b954_plex: 500 Server Error: Internal Server Error 

### ISSUE THREAD

**Issue by reinethernal** [hassio-addons/addon-plex#24]
19-10-05 20:22:45 ERROR (SyncWorker_3) [hassio.docker] Can't start addon_a0d7b954_plex: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_plex (db76e3cbc9236a093e658c9e415d0b695b1caae27568f54557eaf9f6d592ec1a): Bind for 0.0.0.0:33443 failed: port is already allocated")

**Comment by sinclairpaul** [comment]
I would suggest posting a full log, but 0.0.0.0:33443 failed: **port is already allocated** would suggest the port is in use already.

As you haven't specified your OS or what caused the issue, will close as its likely a config issue, not related to an issue with the addon.

**Comment by reinethernal** [comment]
i have a hassio image  installed on rpi 2b+. 

Full log is 

19-10-05 19:43:23 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-rpc_shutdown with version 1.0
19-10-05 19:43:25 ERROR (MainThread) [hassio.addons.addon] Can't restore origin data: [('/data/tmp/tmpyyi5nt23/data/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.lastfm.log', '/data/addons/data/a0d7b954_plex/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.lastfm.log', '[Errno 9] Bad file descriptor')]
19-10-05 19:43:30 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_plex
19-10-05 19:43:31 INFO (MainThread) [hassio.addons.addon] Restore data for addon a0d7b954_zerotier
19-10-05 19:43:44 INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on hassioaddons/motioneye with version 0.5.5
19-10-05 19:43:52 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 6.3.3
19-10-05 19:43:52 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-configurator with version 3.5
19-10-05 19:44:05 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on hassioaddons/zerotier-armv7 with version 0.5.0
19-10-05 19:44:06 INFO (MainThread) [hassio.addons] Detect new Add-on after restore a0d7b954_zerotier
19-10-05 19:44:07 INFO (SyncWorker_17) [hassio.docker.addon] Start Docker add-on hassioaddons/log-viewer-armv7 with version 0.6.4
19-10-05 19:44:16 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_motioneye
19-10-05 19:44:18 INFO (SyncWorker_8) [hassio.docker.addon] Start Docker add-on hassioaddons/grocy-armv7 with version 0.3.2
19-10-05 19:44:25 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_ssh
19-10-05 19:44:28 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_zerotier
19-10-05 19:44:31 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_logviewer
19-10-05 19:44:44 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_grocy
19-10-05 19:45:00 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_motioneye
19-10-05 19:45:02 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_logviewer
19-10-05 19:45:04 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_ssh
19-10-05 19:45:22 INFO (MainThread) [hassio.addons.addon] Restore data for addon core_samba
19-10-05 19:45:31 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_grocy
19-10-05 19:46:05 INFO (SyncWorker_13) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 8.1
19-10-05 19:46:05 INFO (MainThread) [hassio.addons] Detect new Add-on after restore core_samba
19-10-05 19:46:23 INFO (MainThread) [hassio.addons.addon] Restore data for addon a0d7b954_zwave2mqtt
19-10-05 19:47:18 INFO (MainThread) [hassio.addons.addon] Restore config for addon a0d7b954_unifi
19-10-05 19:47:18 INFO (MainThread) [hassio.addons.addon] Restore/Install image for addon a0d7b954_unifi
19-10-05 19:47:18 INFO (SyncWorker_17) [hassio.docker.interface] Pull image hassioaddons/unifi-armv7 tag 0.13.0.
19-10-05 19:47:39 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on hassioaddons/zwave2mqtt-armv7 with version 0.4.0
19-10-05 19:47:39 INFO (MainThread) [hassio.addons] Detect new Add-on after restore a0d7b954_zwave2mqtt
19-10-05 19:47:52 INFO (MainThread) [hassio.addons.addon] Restore data for addon core_letsencrypt
19-10-05 19:47:55 INFO (MainThread) [hassio.addons.addon] Finish restore for add-on core_letsencrypt
19-10-05 19:47:55 INFO (MainThread) [hassio.addons] Detect new Add-on after restore core_letsencrypt
19-10-05 19:47:58 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_zwave2mqtt
19-10-05 19:48:17 INFO (MainThread) [hassio.api.security] /dns/info access from a0d7b954_zwave2mqtt
19-10-05 19:50:33 INFO (MainThread) [hassio.addons.addon] Restore data for addon a0d7b954_sonweb
19-10-05 19:50:53 INFO (SyncWorker_16) [hassio.docker.addon] Start Docker add-on hassioaddons/sonweb-armv7 with version 0.8.2
19-10-05 19:50:53 INFO (MainThread) [hassio.addons] Detect new Add-on after restore a0d7b954_sonweb
19-10-05 19:53:43 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_sonweb
19-10-05 19:56:04 INFO (MainThread) [hassio.addons.addon] Restore data for addon a0d7b954_unifi
19-10-05 19:57:11 ERROR (MainThread) [hassio.addons.addon] Can't restore origin data: [('/data/tmp/tmpenybb52n/data/unifi/data/backup', '/data/addons/data/a0d7b954_unifi/unifi/data/backup', "[Errno 2] No such file or directory: '/data/tmp/tmpenybb52n/data/unifi/data/backup'")]
19-10-05 19:57:12 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_unifi
19-10-05 19:57:12 INFO (MainThread) [hassio.snapshots] Restore faa3a95d wait for Home-Assistant
19-10-05 19:58:01 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant application
19-10-05 19:58:02 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.99.2
19-10-05 19:58:02 INFO (SyncWorker_8) [hassio.docker.interface] Cleanup images: ['homeassistant/raspberrypi2-homeassistant:0.99.3']
19-10-05 19:59:00 INFO (SyncWorker_6) [hassio.docker.homeassistant] Start homeassistant homeassistant/raspberrypi2-homeassistant with version 0.99.2
19-10-05 19:59:46 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-10-05 19:59:46 INFO (MainThread) [hassio.snapshots] Partial-Restore faa3a95d done
19-10-05 20:22:45 ERROR (SyncWorker_3) [hassio.docker] Can't start addon_a0d7b954_plex: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_plex (db76e3cbc9236a093e658c9e415d0b695b1caae27568f54557eaf9f6d592ec1a): Bind for 0.0.0.0:33443 failed: port is already allocated")

**Comment by reinethernal** [comment]
and none of other plugins installed use this port.

**Comment by sinclairpaul** [comment]
Try running `hassio supervisor repair` from your ssh addon, if it fails uninstall and reinstall the addon.  Looks to me that the restore failed.
`19-10-05 19:43:30 ERROR (MainThread) [hassio.snapshots.snapshot] Can't restore snapshot for a0d7b954_plex`

**Comment by sinclairpaul** [comment]
To add, you should be able to open the tar and delete the file `'/data/addons/data/a0d7b954_plex/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.agents.lastfm.log` if you need to restore the data
