### ISSUE TITLE
Automatic subtitles for local media

### ISSUE THREAD

**Issue by baaswietse** [hassio-addons/addon-plex#31]
Hello,

I know this isn't really an issue but I don't know where else to ask since I've been looking at forums all day and didn't get it to work.

I'm trying to get subtitles on my local media (I put in the shared folder), but nothing seems to work.

Has anyone found a solution for this?

Thanks in advance.

**Comment by frenck** [comment]
This is a question that belongs in the Plex forum I would say.
I have no idea... 🤷
