### ISSUE TITLE
Errors with new update

### ISSUE THREAD

**Issue by jimmyz5150** [hassio-addons/addon-plex#32]
# Problem/Motivation

> Getting error after HA Plex update.. when using  HA 107 reworked media player and custom mini player.. Even reverted snapshot to 106.6 and then did plex update, thinking it's HA107.

> Reported HA error: Failed to call service media_player/media_play_pause. syntax error: line 1, column 0

The column # change numbers, I image due to the different devices I have. i.e. column 54?
Works fine for PS4 . error above on Samsung TV , DigiLand Tablet , and Kindle Fire. Haven't tried Visio. 
They still allow control just show up with an error.
With new HA media Control, they controls will generally show up then disappear
I know there were some depreciated items.

Any idea Frenck?
thanks you ur help and time

**Comment by frenck** [comment]
Your question is about the Home Assistant Integration, not the add-on.

Please make sure you raise your issues/questions on the right location.

Thanks 👍
