### ISSUE TITLE
Plex authentication failing

### ISSUE THREAD

**Issue by fredericks1982** [hassio-addons/addon-plex#34]
I've a clean fresh installation of Home Assistant v0.107.7 as a docker container on a QNAP NAS (firmware version: 4.4.1.1216 - amd64 architecture). The Home Assistant instance has docker internal address 10.0.3.2:8123 and is exposed on my LAN with address 192.168.1.xx:327yy. 

When I try to add a Plex Server integration from the Home assistant UI (see picture 01) a new window is opened to authenticate to Plex (see picture 02), but after I authenticate on Plex (see picture 03), I'm redirected to the container internal IP (10.0.3.2, not visible from the LAN) and not to the HASS LAN IP I've started from (192.168.1.xx) - see picture 04, so the integration process on Home Assistant stays waiting for a callback forever (see picture 05). Notice that on my Plex Server instance the new integration token appears correctly (so it is not a Plex login problem).

I would expect instead, after a successful Plex login, to be redirected to my Home Assistant instance LAN IP 192.168.1.xx (from which I started the process) and to successfully complete the Plex integration setup.

Nothing happens on Home Assistant logs (no new lines written during the process).
![01 Start integration configuration](https://user-images.githubusercontent.com/32093333/78877022-8248c180-7a50-11ea-9ee2-ae5bc33c7fc0.png)
![02 Plex login](https://user-images.githubusercontent.com/32093333/78877040-883ea280-7a50-11ea-839a-6a19bdfdf93b.png)
![03 Login OK](https://user-images.githubusercontent.com/32093333/78877047-8bd22980-7a50-11ea-863f-fc884864d4b0.png)
![04 Wrong callback IP address](https://user-images.githubusercontent.com/32093333/78877061-8f65b080-7a50-11ea-8c60-04e36e710f96.png)
![05 HASS still waiting](https://user-images.githubusercontent.com/32093333/78877073-92f93780-7a50-11ea-9d6d-d3fa1a969b6a.png)

**Comment by frenck** [comment]
This is the add-on repository. Your question is about a Home Assistant integration. Those are not related.

Please see: <https://www.home-assistant.io/help> on how to get help and support with Home Assistant itself.

Thanks 👍
