### ISSUE TITLE
add-on won't run

### ISSUE THREAD

**Issue by miketree1** [hassio-addons/addon-plex#36]
# Problem/Motivation

> I've just installed the plex addon, but it won't start
0.110.1
running on Virtualbox

## Expected behavior
runing service

## Actual behavior

20-05-24 11:25:33 ERROR (SyncWorker_1) [supervisor.docker] Can't start addon_a0d7b954_plex: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_a0d7b954_plex (ae566dabcaf55e6a12a3e8e97094b3d0cd6efd5c3ba861bef04c6a2fa7b73f07): Error starting userland proxy: listen udp 0.0.0.0:1900: bind: address already in use")

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
> 1900: bind: address already in use

Port 1900 is already in use. A port can only be used once. Either disable the port by making the field empty, or free up the port.
