### ISSUE TITLE
USB Disk

### ISSUE THREAD

**Issue by hugodelaroza** [hassio-addons/addon-plex#37]
# Problem/Motivation
I want to mount my movies library un a USB hard drive

> (Why the issue was filed)
I installed this addon and saved some movies on a USB hard drive. I want to share the drive with samba and map my plex libraries in this. I think that it is possible to map the disk as a volume with portainer addon and take it to share with samba addon and use it as the location for the library of my plex addon.
I´m new on portainwe and docker, I don´t know how, but I think it´s possible to do it.

Can anybody help me?
## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This add-on does not support mounting external or additional drives.
