### ISSUE TITLE
Add shared server

### ISSUE THREAD

**Issue by jonastaedcke** [hassio-addons/addon-plex#44]
# Problem/Motivation

Add shared server

## Expected behavior

Add the shared sever in the same way as my local server to get his Activity Sensor

## Actual behavior

The installation of this server stoped and canceled. There is no way to add this server to home-assistant.
The integration page shows a new box to finish the installation. But after authentication the installation failed. 

## Steps to reproduce

Try to add a shared server via the integration page

## Proposed changes

- get media_player for devices who played things from the shared server within my local server
- hide shared server from the configuration list

**Comment by frenck** [comment]
Could you explain yourself a bit more? I got the feeling you are talking about the Home Assistant Plex integration?
The add-on just runs Plex, plain dead simple. Not sure what you want me to add in this case?
