### ISSUE TITLE
Map external shares to server

### ISSUE THREAD

**Issue by arseni-mik** [hassio-addons/addon-plex#46]
# Problem/Motivation

> I'm running Hassio on a raspberry pi 4. Since SD card storage is limited I'd like to be able to map a nas share to the Plex Server to the Plex addon/container

## Expected behavior

> Since Addons are basically just docker containers I would expect be able to use the -v volume comand or volumes in the docker compose to map whatever storage you want ex:
  -v /path/to/tvseries:/tv 
      -->  -v //NasIp/share/on/NAS:/share/in/addon
## Actual behavior

> Currently you can't set that configuration

## Steps to reproduce

> na

## Proposed changes

> I have not been able to figue out how to do a mount command when starting the container as an addon yet.

**Comment by frenck** [comment]
The add-on doesn't support it, because the underlying system the add-on runs on doesn't support that.
Cannot change anything about it from an add-on perspective.
