### ISSUE TITLE
Problem - server not showing up - 'no soup for you'

### ISSUE THREAD

**Issue by weaklund** [hassio-addons/addon-plex#62]
# Problem/Motivation
>My new PMS (installed as addon via supervisor in hassio) is not showing up when i login to the web interface.

## Expected behavior

> I expected the setup wizard when loging in to my the PMS_IP:32400/web

## Actual behavior

> The text "No soup for you!" showed and i cant access the server. I see my other server tough, running on my other windows VM.

**Comment by brendanpward** [comment]
Same issue for me.  I've tried logging in and out, clearing all my authorized devices, reinstalling, and getting a new claim code.  Set logging to Debug level, but it shows nothing in the logs when I log in and get the 'no soup for you' error.  Sign out, log in again and I don't have any access to the server controls.  I go to the webtools to search for folders and nothing is listed in the 'Findmedia' tab.

 Add-on version: 2.5.1
 System: Home Assistant OS 5.11  (amd64 / qemux86-64)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6

**Comment by frenck** [comment]
Meh, I'm not able to reproduce at this point 😢

**Comment by carloss66** [comment]
I am having the same problem on core-2021.2.3.

**Comment by brendanpward** [comment]
I gave up for a few days then came back to trying again today.  It seems I made the mistake of starting the server before claiming it.  Here's my solution:
1. Completely uninstall the add-on.
2. Most importantly, get a claim code before doing anything else!
3. Install the add-on again but do not start
4. Enter the claim code on the configuration page
5. Start the server
.
It's pretty silly to me that it would cause this much of an issue if it does't have the claim code right off the hop.  Entering the code and doing a restart should fix it without having to do a complete reinstall . . . but that's just my two cents.  I guess it's also my fault for not following the instructions down to the letter.

**Comment by carloss66** [comment]
@brendanpward That worked!

**Comment by ConsolaViejuna** [comment]
Wroks great @brendanpward , I had the same problem, thank you very much!

**Comment by dessmith** [comment]
Great, works for me too. Think I had issues as I had AirSonos running that uses port 1900 conflicts with Plex that causes a problem with the default config

**Comment by frenck** [comment]
The issue is caused by the base image, opened up a PR to address it for the next release.
