### ISSUE TITLE
"WARNING: Protection mode is ON. Unable to mount external drivers!" & "Port 'X' is already in use by something else on the host."

### ISSUE THREAD

**Issue by LoganJFisher** [hassio-addons/addon-plex#63]
# Problem/Motivation

> When starting the Plex Media Server with NAS addon, my log gives the error: "WARNING: Protection mode is ON. Unable to mount external drivers!" despite having protection mode toggled off.

> When starting the Plex Media Server addon after starting the Plex Media Server with NAS addon (as per the documentation for Plex Media Server with NAS addon), I am greeted with the error: "Port 'X' is already in use by something else on the host.", where "X" is one of the various ports listed within the configuration for either addon.

## Expected behavior

> I expected to not get a protection mode on warning.

> I expected the Plex Media Server addon to start normally after starting the Plex Media Server with NAS addon.

## Actual behavior

> Described above.

## Steps to reproduce

> Uncertain

## Proposed changes

> None. Help needed.

**Comment by sinclairpaul** [comment]
This addon doesn't issue that log message, where did you install it from?

**Comment by LoganJFisher** [comment]
> 
> 
> This addon doesn't issue that log message, where did you install it from?

I got it from this repository: https://github.com/dianlight/hassio-addons

**Comment by sinclairpaul** [comment]
Then I would suggest that you log the issue at that repo 😉

**Comment by LoganJFisher** [comment]
Oh, odd. This is the repo linked in the documentation for that addon.

**Comment by sinclairpaul** [comment]
Yeah as its a fork, and the maintainer didn't update it.  Unfortunately there is nothing we can do here for you.
