### ISSUE TITLE
add a network location to plex

### ISSUE THREAD

**Issue by mhusny** [hassio-addons/addon-plex#69]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is an empty issue, so there is no issue to fix. Feel free to open a new issue with contents. Thanks! 👍
