### ISSUE TITLE
Could not resolve host: plex.tv error

### ISSUE THREAD

**Issue by tbone004** [hassio-addons/addon-plex#7]
First off I am trying to add this add-on using Hassio and Ubuntu, this may not be support.

Plex add-on will not start, it is giving me a "Could not resolve host: plex.tv". I tried to ping plex.tv and can't, but I can ping www.plex.tv. What am I missing.

The claim code was copied and pasted from plex.tv seconds before clicking start so I know it is correct and current.

-----------------------------------------------------------
 amd64 / Ubuntu 18.04.1 LTS / HA 0.77.2 / SU 128 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-first-run.sh: executing... 
INFO: First run! Initializing configuration files...
curl: (6) Could not resolve host: plex.tv
FATAL: Something went wrong contacting the Plex API
FATAL: Maybe your claim code is wrong or expired?
[cont-init.d] 10-first-run.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.
 
 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.

Thanks
Tim

**Comment by ludeeus** [comment]
It looks like you have DNS issues.
On the host change or create this file `/etc/docker/daemon.json`
With this content:
```json
{
    "dns": ["10.0.0.1", "8.8.8.8"]
}
```
Change `"10.0.0.1"` to your router IP, and `"8.8.8.8"` if you want to use another service, `8.8.8.8` is Google's public DNS service.

**Comment by tbone004** [comment]
Thanks for your reply, this fixed my issue. Plex is now up and running.
