### ISSUE TITLE
Feature Request: add configuration option to optionally mount SMB/CIFS share

### ISSUE THREAD

**Issue by met67** [hassio-addons/addon-plex#70]
# Problem/Motivation

When using Home Assistant OS, the add-on is almost useless since it can't mount any media folder.
It would be nice to implement a configuration option to mount external media folder via SMB/CIFS if the user disable "Protection Mode".
There is a technically feasible solution to this problem (e.g. https://github.com/dianlight/addon-plex)

## Expected behavior

When using Home Assistant OS, I would expect to be able to disable Protection Mode in the add-on, define some media share in config and have them mounted at run-time in the add-on filesystem.

## Actual behavior

It is not possible to mount any external media in Home Assistan OS.

## Steps to reproduce

Nothing.

## Proposed changes

Implement something similar to https://github.com/dianlight/addon-plex

**Comment by frenck** [comment]
This should not be a job for the add-on, but for the Supervisor or Host OS. I'm not adding that feature to the add-on.

**Comment by lbouriez** [comment]
I get your point @frenck  but this feature has been requested for this addon since forever... and hassio doesnt offer it out of the box :/
If there is already someone who offer a solution, why not implement it in the meantime to make us all happy ?

**Comment by frenck** [comment]
> If there is already someone who offer a solution, why not implement it in the meantime to make us all happy ?

Because it will cause problems and adds maintenance, that I'm not willing to provide support or time for.
