### ISSUE TITLE
DLNA does not work

### ISSUE THREAD

**Issue by condio** [hassio-addons/addon-plex#72]
# Problem/Motivation

> DLNA on HASSIO does not work. According to an old issue, the Addon needs to change its networking default to use host networking. https://github.com/hassio-addons/addon-plex/issues/28

## Expected behavior

> Computers and systems in home should see DLNA server.

## Actual behavior

> Plex not found.

## Steps to reproduce

> Enable DLNA. Notice that it doesn't work.

## Proposed changes

> Can this be fixed so the Addon works with DLNA for everyone without the need to hack this into a Portainer?

**Comment by frenck** [comment]
Yes, it required changes to the add-on.

PS: Please don't use the term "hass.io" in general, as it doesn't exist anymore and is ambiguous.

**Comment by emre299** [comment]
> Evet, eklentide değişiklik yapılması gerekiyordu.
> 
> Not: Artık mevcut olmadığı ve belirsiz olduğu için lütfen "hass.io" terimini genel olarak kullanmayın.



> Yes, it required changes to the add-on.
> 
> PS: Please don't use the term "hass.io" in general, as it doesn't exist anymore and is ambiguous.

How can I make a change for the dlna work? thanks
